"""nutrition memory: user macros per dish

Revision ID: 1b5b3749a97a
Revises: 1de732e0c11b
Create Date: 2026-08-24 17:16:05.538473
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1b5b3749a97a'
down_revision = '1de732e0c11b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_norm', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('portion_g', sa.Float(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_nutrition_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_nutrition')),
    sa.UniqueConstraint('user_id', 'key_norm', name='uq_nutrition_user_key')
    )
    op.create_index('ix_nutrition_lookup', 'user_nutrition', ['user_id', 'key_norm'], unique=False)
    op.create_index(op.f('ix_user_nutrition_user_id'), 'user_nutrition', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_nutrition_user_id'), table_name='user_nutrition')
    op.drop_index('ix_nutrition_lookup', table_name='user_nutrition')
    op.drop_table('user_nutrition')
    # ### end Alembic commands ###
