"""meds, personal dictionary, settings_kv

Revision ID: 1de732e0c11b
Revises: f469fdb8a826
Create Date: 2026-08-24 11:18:40.694641
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1de732e0c11b'
down_revision = 'f469fdb8a826'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_kv',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings_kv'))
    )
    op.create_table('user_dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key_norm', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_dictionary_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_dictionary')),
    sa.UniqueConstraint('user_id', 'kind', 'key_norm', name='uq_dictionary_user_kind_key')
    )
    op.create_index('ix_dictionary_lookup', 'user_dictionary', ['user_id', 'kind', 'key_norm'], unique=False)
    op.create_index(op.f('ix_user_dictionary_user_id'), 'user_dictionary', ['user_id'], unique=False)
    # batch mode: SQLite cannot ALTER ... ADD CONSTRAINT, and `source` needs a
    # server default so the column can land NOT NULL on an existing journal.
    with op.batch_alter_table('medications') as batch:
        batch.add_column(sa.Column('slug', sa.String(length=128), nullable=True))
        batch.add_column(sa.Column('cid', sa.String(length=16), nullable=True))
        batch.add_column(sa.Column('form', sa.String(length=64), nullable=True))
        batch.add_column(
            sa.Column('source', sa.String(length=16), nullable=False, server_default='text')
        )
        batch.add_column(sa.Column('media_id', sa.Integer(), nullable=True))
        batch.create_index(batch.f('ix_medications_slug'), ['slug'], unique=False)
        batch.create_index('ix_medications_user_taken', ['user_id', 'taken_at'], unique=False)
        batch.create_foreign_key(
            batch.f('fk_medications_media_id_media_files'),
            'media_files',
            ['media_id'],
            ['id'],
            ondelete='SET NULL',
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications') as batch:
        batch.drop_constraint(
            batch.f('fk_medications_media_id_media_files'), type_='foreignkey'
        )
        batch.drop_index('ix_medications_user_taken')
        batch.drop_index(batch.f('ix_medications_slug'))
        batch.drop_column('media_id')
        batch.drop_column('source')
        batch.drop_column('form')
        batch.drop_column('cid')
        batch.drop_column('slug')
    op.drop_index(op.f('ix_user_dictionary_user_id'), table_name='user_dictionary')
    op.drop_index('ix_dictionary_lookup', table_name='user_dictionary')
    op.drop_table('user_dictionary')
    op.drop_table('settings_kv')
    # ### end Alembic commands ###
