"""notifications: templates, prefs, sends

Revision ID: 9a219bc869d7
Revises: d51aa877105e
Create Date: 2026-09-12 08:41:23.577427
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9a219bc869d7'
down_revision = 'd51aa877105e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('times', sa.String(length=128), nullable=False),
    sa.Column('signal', sa.String(length=128), nullable=False),
    sa.Column('lead_min', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_notification_templates_code'))
    )
    op.create_table('notification_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('times', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_prefs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_prefs')),
    sa.UniqueConstraint('user_id', 'code', name='uq_notify_pref_user_code')
    )
    op.create_index(op.f('ix_notification_prefs_user_id'), 'notification_prefs', ['user_id'], unique=False)
    op.create_table('notification_sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('slot', sa.String(length=8), nullable=False),
    sa.Column('sent_on', sa.String(length=10), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_sends_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_sends')),
    sa.UniqueConstraint('user_id', 'code', 'slot', 'sent_on', name='uq_notify_send_slot')
    )
    op.create_index(op.f('ix_notification_sends_user_id'), 'notification_sends', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_sends_user_id'), table_name='notification_sends')
    op.drop_table('notification_sends')
    op.drop_index(op.f('ix_notification_prefs_user_id'), table_name='notification_prefs')
    op.drop_table('notification_prefs')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
