"""initial schema

Revision ID: f469fdb8a826
Revises: 
Create Date: 2026-08-24 08:39:59.232904
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f469fdb8a826'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('glucose_unit', sa.String(length=8), nullable=False),
    sa.Column('sensor', sa.String(length=64), nullable=True),
    sa.Column('window_1h_start', sa.Integer(), nullable=False),
    sa.Column('window_1h_end', sa.Integer(), nullable=False),
    sa.Column('window_2h_start', sa.Integer(), nullable=False),
    sa.Column('window_2h_end', sa.Integer(), nullable=False),
    sa.Column('baseline_window', sa.Integer(), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('activity_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_samples_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_samples')),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_activity_external')
    )
    op.create_index(op.f('ix_activity_samples_user_id'), 'activity_samples', ['user_id'], unique=False)
    op.create_index('ix_activity_user_start', 'activity_samples', ['user_id', 'start_at'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_corrections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrections'))
    )
    op.create_index(op.f('ix_corrections_user_id'), 'corrections', ['user_id'], unique=False)
    op.create_table('food_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_type', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('window', sa.String(length=8), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('mean_delta', sa.Float(), nullable=True),
    sa.Column('median_delta', sa.Float(), nullable=True),
    sa.Column('max_delta', sa.Float(), nullable=True),
    sa.Column('ci_low', sa.Float(), nullable=True),
    sa.Column('ci_high', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_food_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_stats')),
    sa.UniqueConstraint('user_id', 'key_type', 'key', 'window', name='uq_food_stats_key')
    )
    op.create_index(op.f('ix_food_stats_user_id'), 'food_stats', ['user_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tg_file_id', sa.String(length=256), nullable=True),
    sa.Column('tg_unique_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_media_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files'))
    )
    op.create_index(op.f('ix_media_files_sha256'), 'media_files', ['sha256'], unique=False)
    op.create_index(op.f('ix_media_files_tg_unique_id'), 'media_files', ['tg_unique_id'], unique=False)
    op.create_index(op.f('ix_media_files_user_id'), 'media_files', ['user_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dose_text', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    op.create_index(op.f('ix_medications_user_id'), 'medications', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_norm', sa.String(length=256), nullable=False),
    sa.Column('kcal_100', sa.Float(), nullable=True),
    sa.Column('protein_100', sa.Float(), nullable=True),
    sa.Column('fat_100', sa.Float(), nullable=True),
    sa.Column('carbs_100', sa.Float(), nullable=True),
    sa.Column('sugars_100', sa.Float(), nullable=True),
    sa.Column('fiber_100', sa.Float(), nullable=True),
    sa.Column('ingredients_text', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('additives', sa.JSON(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_products_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_name_norm'), 'products', ['name_norm'], unique=False)
    op.create_index('ix_products_user_name', 'products', ['user_id', 'name_norm'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_symptoms_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptoms')),
    sa.UniqueConstraint('user_id', 'slug', name='uq_symptoms_user_slug')
    )
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weights'))
    )
    op.create_index(op.f('ix_weights_user_id'), 'weights', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('panel', sa.String(length=128), nullable=True),
    sa.Column('marker', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('ref_low', sa.Float(), nullable=True),
    sa.Column('ref_high', sa.Float(), nullable=True),
    sa.Column('flag', sa.String(length=16), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_analysis_results_media_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analysis_results_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results'))
    )
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    op.create_index('ix_analysis_user_marker', 'analysis_results', ['user_id', 'marker'], unique=False)
    op.create_table('glucose_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_mmol', sa.Float(), nullable=False),
    sa.Column('unit_input', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_glucose_readings_media_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_glucose_readings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glucose_readings')),
    sa.UniqueConstraint('user_id', 'measured_at', 'value_mmol', name='uq_glucose_point')
    )
    op.create_index(op.f('ix_glucose_readings_user_id'), 'glucose_readings', ['user_id'], unique=False)
    op.create_index('ix_glucose_user_time', 'glucose_readings', ['user_id', 'measured_at'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eaten_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('corrected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_meals_media_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_index('ix_meals_user_eaten', 'meals', ['user_id', 'eaten_at'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('product_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_product_photos_media_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_photos_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_photos'))
    )
    op.create_index(op.f('ix_product_photos_product_id'), 'product_photos', ['product_id'], unique=False)
    op.create_table('wellbeing_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], name=op.f('fk_wellbeing_checkins_media_id_media_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wellbeing_checkins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wellbeing_checkins'))
    )
    op.create_index('ix_checkins_user_at', 'wellbeing_checkins', ['user_id', 'at'], unique=False)
    op.create_index(op.f('ix_wellbeing_checkins_user_id'), 'wellbeing_checkins', ['user_id'], unique=False)
    op.create_table('checkin_symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['wellbeing_checkins.id'], name=op.f('fk_checkin_symptoms_checkin_id_wellbeing_checkins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name=op.f('fk_checkin_symptoms_symptom_id_symptoms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkin_symptoms'))
    )
    op.create_index(op.f('ix_checkin_symptoms_checkin_id'), 'checkin_symptoms', ['checkin_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_norm', sa.String(length=256), nullable=False),
    sa.Column('portion_g', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_items_meal_id_meals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_meal_items_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_items'))
    )
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    op.create_index('ix_meal_items_norm', 'meal_items', ['name_norm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meal_items_norm', table_name='meal_items')
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_checkin_symptoms_checkin_id'), table_name='checkin_symptoms')
    op.drop_table('checkin_symptoms')
    op.drop_index(op.f('ix_wellbeing_checkins_user_id'), table_name='wellbeing_checkins')
    op.drop_index('ix_checkins_user_at', table_name='wellbeing_checkins')
    op.drop_table('wellbeing_checkins')
    op.drop_index(op.f('ix_product_photos_product_id'), table_name='product_photos')
    op.drop_table('product_photos')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index('ix_meals_user_eaten', table_name='meals')
    op.drop_table('meals')
    op.drop_index('ix_glucose_user_time', table_name='glucose_readings')
    op.drop_index(op.f('ix_glucose_readings_user_id'), table_name='glucose_readings')
    op.drop_table('glucose_readings')
    op.drop_index('ix_analysis_user_marker', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_weights_user_id'), table_name='weights')
    op.drop_table('weights')
    op.drop_table('symptoms')
    op.drop_index('ix_products_user_name', table_name='products')
    op.drop_index(op.f('ix_products_name_norm'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_medications_user_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_media_files_user_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_tg_unique_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_sha256'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_food_stats_user_id'), table_name='food_stats')
    op.drop_table('food_stats')
    op.drop_index(op.f('ix_corrections_user_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index('ix_activity_user_start', table_name='activity_samples')
    op.drop_index(op.f('ix_activity_samples_user_id'), table_name='activity_samples')
    op.drop_table('activity_samples')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
